spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-route
          uri: lb://authentication-service
          predicates:
          - Path=/auth/**
          filters:
          - RewriteLocationResponseHeader=AS_IN_REQUEST
#          - Authorize=false
management:
  endpoint:
    gateway:
      enabled: true